package com.appersiano.goustoexercise.repository.ormlite.model;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

/**
 * Try to make a clean object
 */
@DatabaseTable(tableName = "product_attribute")
public class ProductAttribute {

    public final static String PRODUCT_ID_FIELD_NAME = "product_id";
    public final static String ATTRIBUTE_ID_FIELD_NAME = "attribute_id";

    /**
     * This id is generated by the database and set on the object when it is passed to the create method. An id is
     * needed in case we need to update or delete this object in the future.
     */
    @DatabaseField(generatedId = true)
    int id;

    // This is a foreign object which just stores the id from the User object in this table.
    @DatabaseField(foreign = true, columnName = PRODUCT_ID_FIELD_NAME)
    Product product;

    // This is a foreign object which just stores the id from the Post object in this table.
    @DatabaseField(foreign = true, columnName = ATTRIBUTE_ID_FIELD_NAME)
    Attribute attribute;

    ProductAttribute() {
        // for ormlite
    }

    public ProductAttribute(Product product, Attribute attribute) {
        this.product = product;
        this.attribute = attribute;
    }
}