package com.appersiano.goustoexercise.repository.ormlite.model;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

/**
 * Try to make a clean object
 */
@DatabaseTable(tableName = "product_category")
public class ProductCategory {

    public final static String PRODUCT_ID_FIELD_NAME = "product_id";
    public final static String CATEGORY_ID_FIELD_NAME = "category_id";

    /**
     * This id is generated by the database and set on the object when it is passed to the create method. An id is
     * needed in case we need to update or delete this object in the future.
     */
    @DatabaseField(generatedId = true)
    int id;

    // This is a foreign object which just stores the id from the User object in this table.
    @DatabaseField(foreign = true, columnName = PRODUCT_ID_FIELD_NAME)
    Product product;

    // This is a foreign object which just stores the id from the Post object in this table.
    @DatabaseField(foreign = true, columnName = CATEGORY_ID_FIELD_NAME)
    Category category;

    ProductCategory() {
        // for ormlite
    }

    public ProductCategory(Product product, Category category) {
        this.product = product;
        this.category = category;
    }
}